#REPLACED BY [Probot - Welcome](https://github.com/apps/welcome)

name: PR Greetings

on: 
  pull_request:
    types: 
    - opened
    - assigned
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Print variables
      run: |
        echo "github.event.action - ${{ github.event.action }}"
        echo "github.actor - ${{ github.actor }}"
        echo "github.event_name - ${{ github.event_name }}"
        echo "github.ref - ${{ github.ref }}"

    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # issue-message: |
        #   # Welcome ${{github.actor}} ❤️! 🎉🍕
        #   Congrats to your _first issue_!
        #   **It is essential that you read the [developer guide](https://github.com/stefanini-applications/developer-guide).**
        
        pr-message: |
          # Welcome ${{github.actor}} ❤️! 🎉🍕
          Congrats to your _first PR_!
          **It is essential that you read the [developer guide](https://github.com/stefanini-applications/developer-guide).**
