name: CI - On Release

on:
  push:
    branches: 
      - master
      - 'release/**'
    paths-ignore: 
      - '**.md'
      - 'docs/**'
      - 'db/**'
      - 'pipelines/**'

jobs:
  build-and-test:
    name: Build 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
    - uses: actions/checkout@v2

    - name: Print variables
      run: |
        echo "github.event.action >> ${{ github.event.action}}"
        echo "github.actor >> ${{ github.actor}}"
        echo "github.event_name >> ${{ github.event_name}}"
        echo "github.ref >> ${{ github.ref}}"