name: CI

on:
  push:
    branches: 
      - master
      - 'feat/**'
  pull_request:
    branches: 
      - master
      - 'feat/**' 
  workflow_dispatch:
    inputs:
      config_deploy:
        default: release
        type: choice
        options:
        - release
        - debug 
        required: true
        description: A configuração a ser usada para compilar o projeto."

      versionTag:
        description: 'Version Tag (semantic version)'
        default: '1.0.0'
        required: false

env:
  #OUTPUT_PATH: ${{ github.workspace }}/.output
  NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
  DOTNET_VERSION: '6.0.x'
  BUILD_NUMBER: ${{ github.event.inputs.versionTag }}
  CONFIG_DEPLOY: ${{ github.event.inputs.config_deploy }}

jobs:
  build-and-deploy:
    name: Build and deploy nuget
    runs-on: ubuntu-latest
    steps:
    - name: teste
      run: |
        echo "config_deploy:${{inputs.config_deploy}}"
        echo "versionTag:${{inputs.versionTag}}"

    - uses: actions/checkout@v2

    - name: Define build number if empty
      run: echo "BUILD_NUMBER=1.0.${{ github.run_number }}" >> $GITHUB_ENV
      if: ${{ env.BUILD_NUMBER == '' }}

    - name: Define configuration deploy if empty
      run: echo "CONFIG_DEPLOY=release" >> $GITHUB_ENV
      if: ${{ env.CONFIG_DEPLOY == '' }}

    - name: Setup .NET v${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore --configfile NuGet.Config
      
    - name: Build
      run: dotnet build --no-restore -c ${{ env.CONFIG_DEPLOY }} -p:VersionSuffix=${{ env.BUILD_NUMBER }} /nr:false

    - name: Pack
      run: dotnet pack --no-build -c ${{ env.CONFIG_DEPLOY }} -p:VersionSuffix=${{ env.BUILD_NUMBER }} /nr:false -o .
        
    - name: Push
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.NUGET_SOURCE }} --skip-duplicate    

    