name: Label by directory

on:
  pull_request_target:
    types: 
    - opened
    - reopened
    - synchronize

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:

    - uses: TimonVS/pr-labeler-action@v3
      with:
        configuration-path: .github/label-directory-config.yml # optional, .github/pr-labeler.yml is the default value
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}