name: Label by directory

on:
  pull_request_target:
    types: 
    - opened
    - reopened
    - synchronize

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Print variables
      runs: |
        echo "github.event.action >> ${{ github.event.action}}"
        echo "github.actor >> ${{ github.actor}}"
        echo "github.event_name >> ${{ github.event_name}}"
        echo "github.ref >> ${{ github.ref}}"
        
    - uses: TimonVS/pr-labeler-action@v3
      with:
        configuration-path: .github/label-directory-config.yml # optional, .github/pr-labeler.yml is the default value
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}