name: "Pull Request Labeler"

on:
  pull_request_target:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: TimonVS/pr-labeler-action@v3
      with:
        configuration-path: .github/config-pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}